apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-dev
nameSuffix: -dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - secret-patch.yaml
