# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-dev          # los objetos vivirán aquí
nameSuffix: -dev              # añade “-dev” a TODOS los nombres

resources:
  - ../../base                # Deployment, Service y Secret de la capa base
  - namespace.yaml            # único Namespace de este overlay

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: redis
  - path: secret-patch.yaml
    target:
      kind: Secret
      name: conexion

