apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-dev
nameSuffix: -dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: redis

  - path: service-patch.yaml
    target:
      kind: Service
      name: redis

  - path: secret-patch.yaml
    target:
      kind: Secret
      name: conexion

