# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-dev          # ← el destino Kubernetes
nameSuffix: -dev              # ← sufijo añadido a *todos* los objetos

resources:
  - ../../base                # capa base (ya corregida)
  - namespace.yaml            # único Namespace de este overlay

patches:                      # 🡇 lista de parches con selectors
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: redis             # ← nombre ORIGINAL (sin sufijo)

  - path: service-patch.yaml
    target:
      kind: Service
      name: redis

  - path: secret-patch.yaml
    target:
      kind: Secret
      name: conexion
