# overlays/dev/service-patch.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis                 # sin sufijo: el selector -dev lo añade Kustomize
spec:
  ports:
  - name: redis
    port: 6377                # expone 6377 → 6379
    targetPort: 6379


