apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-pro
nameSuffix: -pro

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - secret-patch.yaml
